### ISSUE TITLE
GUI broken?

### ISSUE THREAD

**Issue by diminDDL** [GitJer/Some_RPI-Pico_stuff#12]
I don't know if this is an issue on my side but since the interface changed I have parts of the GUI cut off by the window. As well as some text values being cut off weirdly. I am running python 3.8.10 on KDE neon 5.25. I tried to look in to the code but I didn't find anything looking out of place, also I am not familiar with tk enough to know. Any ideas what I could try to fix this? Changing the window size does nothing...
![image](https://user-images.githubusercontent.com/25513498/185204697-e312fbc8-3110-4f31-8ad7-10c275043271.png)

**Comment by GitJer** [comment]
I'm not all that good in tkinter myself. 

Can you try to add in ```interface/__init__.py``` the geometry such that it looks like:
```
# Make the window
self.root = Tk()
self.root.geometry("1570x770")
# Make the title that will appear in the top left
self.root.wm_title("Raspberry PI PICO PIO Emulation")
```
For me, that displays the whole window and it allows resizing. 

That probably doesn't solve the misalignment in the frame with "Clock=0" on top. That frame is built in the file ```interface/_mid_frame.py```. It calls various UI elements in ```interface/_interface_item.py```. In that file, in the class "Interface_Item" a width parameter is set. I suspect that it goes wrong with the width somehow. You can try to set the widths in calls such as 
```super().__init__(frame, display_name, row, col, 40)```
in ```class Var_List``` and  ```class Var_List_IRQ```. Try changing the number 40.

**Comment by diminDDL** [comment]
I tried that on my own already but it doesn't help, even if I set a higher window size like 1800x800 the added space is just filled with white (same as when I try to resize). Changing values in ` super().__init__(frame, display_name, row, col, 40)` did do something so I will have to investigate that further and try to find optimal values for me. (But tbh viewing the FIFOs is more important to be atm, the small snippets shown for the names of the variables are currecntly sufficient for me to guess what it is). Below is what a higher window size looks like.
![image](https://user-images.githubusercontent.com/25513498/185617081-11faa587-a38c-4e05-9b27-8fb96ba80616.png)

**Comment by GitJer** [comment]
I'm not sure what the cause is. I'm using:
Linux Mint 20.3 Cinnamon
python 3.8.10
tkinter 8.6.10

Could there be an issue with the fonts that are used? I noticed that in  ```_mid_frame.py``` I use a specific font. Maybe just after ```self.root = Tk()``` you can set a default font by ```self.root.option_add("*Font", "aerial 10")```. That doesn't help with the misalignment, but maybe it does help with the missing information.

**Comment by diminDDL** [comment]
Yeah this is very weird since I am using the exact same python and tk version, the for setting didn't do anything unfortunately. I guess I'll try to look in to it later and maybe submit a PR if I manage to get down to the origin of this.

**Comment by GitJer** [comment]
no reactions in a year -> close
