### ISSUE TITLE
Cmake errors

### ISSUE THREAD

**Issue by w9ran** [GitJer/Some_RPI-Pico_stuff#13]
I get the following error when using cmake -G "NMake Makefiles" ..  from the DCP :

CMake Error at CMakeLists.txt:3 (pico_generate_pio_header):
  Unknown CMake command "pico_generate_pio_header".

Any suggestions would be appreciated at I'd like to evaluated several of the examples, thanks.

Bob

**Comment by GitJer** [comment]
I have followed the instructions in the ["Getting started with Raspberry Pi Pico"](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) (more than a year ago). The SDK works with CMake. I'm not a fan of CMake, and don't know much about it.
