### ISSUE TITLE
missing header file

### ISSUE THREAD

**Issue by smithps** [GitJer/Some_RPI-Pico_stuff#2]
In the example for the rotary encoder, the cpp file includes "pio_rotary_encoder.pio.h", but this is not in the example directory. I assume this in turn includes and encapsulates the file "pio_rotary_encoder.pio"

It would be useful for beginners if you could also include some CMakelist.txt files to build the examples.

**Comment by smithps** [comment]
My mistake, being a wally. Sorry.

I would delete this "issue" if I could, but can't find the option.

**Comment by GitJer** [comment]
I added the Makefiles anyway!
Making things handy for beginners is something I strive for (but not always actually do). Not so much for the beginners, but I know that if I do not look at my code for half a year, I hardly understand any of it anymore. So, I use a lot of comments. And I agree, the knowledge that the pio.h files are generated might be lost as well.
