### ISSUE TITLE
emulator jmp decrement

### ISSUE THREAD

**Issue by odewdney** [GitJer/Some_RPI-Pico_stuff#6]
From the documentation, X/Y is always decremented on the conditional jump (verified with loop on actual hardware). I updated my code to:
```
        elif jmp_condition == 2:    # x--
            if self.vars["x"] != 0:
                do_jump = True
            self.vars["x"] = (self.vars["x"] - 1) & 0xffffffff

```
same for y

**Comment by GitJer** [comment]
Yep, it says "X--: scratch X non-zero, post-decrement". I corrected it. Good catch, Thanks!
