### ISSUE TITLE
Emulator stops working after 499 clock cycles

### ISSUE THREAD

**Issue by dimonDDL** [GitJer/Some_RPI-Pico_stuff#8]
I really enjoy the emulator, however whenever the clock reaches 499 cycles it just stops and doesn't execute any further. Is it possible to fix this behavior. Or at least point me in the direction so that I can do a pull request if I manage to fix it.

**Comment by GitJer** [comment]
That is good to hear!
I think that if you change the line "my_emulation.emulate(500)" in main.py to a higher number everything should be OK.

**Comment by dimonDDL** [comment]
Ok yeah it does work, but as far as I understood the simulation happens before the program is actually displaying anything. So keeping that in mind I set mine to 5000 and that's enough for me. If you need more you can set more, just need to wait for a while.
Thank you.
