### ISSUE TITLE
Possibility to achknowlege or set the IRQ register throught the C-program in the simulator.

### ISSUE THREAD

**Issue by dimonDDL** [GitJer/Some_RPI-Pico_stuff#9]
Is it possible to somehow acknowledge the interrupts set by the state machine in the simulation? Or just reset it all to zeros with a command in the C program file (same way as you can put data in the FIFOs)?

**Comment by GitJer** [comment]
Hi dimonDDL,

Sorry for the late reply!
I have added some code to allow clearing irqs, see [here](https://github.com/GitJer/Some_RPI-Pico_stuff/tree/main/state_machine_emulator/examples/irq_set_and_clear).

**Comment by dimonDDL** [comment]
This is great. Thanks a lot.
